/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2vr9hQFY2mN9rEqhWxcPmu

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { ContentStackCredentialsProvider } from "@plasmicpkgs/plasmic-content-stack";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  contentStackCredentialsProviderProps?: Partial<
    Omit<
      React.ComponentProps<typeof ContentStackCredentialsProvider>,
      "children"
    >
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, contentStackCredentialsProviderProps } = props;

  return (
    <ContentStackCredentialsProvider
      {...contentStackCredentialsProviderProps}
      accessToken={
        contentStackCredentialsProviderProps &&
        "accessToken" in contentStackCredentialsProviderProps
          ? contentStackCredentialsProviderProps.accessToken!
          : "cs5b69faf35efdebd91d08bcf4"
      }
      apiKey={
        contentStackCredentialsProviderProps &&
        "apiKey" in contentStackCredentialsProviderProps
          ? contentStackCredentialsProviderProps.apiKey!
          : "blt02f7b45378b008ee"
      }
      environment={
        contentStackCredentialsProviderProps &&
        "environment" in contentStackCredentialsProviderProps
          ? contentStackCredentialsProviderProps.environment!
          : "production"
      }
    >
      {children}
    </ContentStackCredentialsProvider>
  );
}
